image: ubuntu:latest

stages: 
    - deploy

static-webpage:
    stage: deploy
    script:
        - mkdir public
        - mv ressources/index.html ./public
    artifacts:
        paths:
            - public
    only:
        - master
